---
<<<<<<< HEAD
blank_issues_enabled: true
=======
blank_issues_enabled: false
contact_links:
  - name: Open up a blank issue
    url: https://github.com/eclipse-dataspaceconnector/docs/issues/new
    about: Don’t see your issue here? Open up a blank one
  - name: Ask a question or get support
    url: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/categories/q-a
    about: Ask a question or request support for using the Eclipse Dataspace Connector
>>>>>>> 2bab874 (chore: provide initial files)
